// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/AndrewOvvv/spawnling/internal/runtime"
)

// MockRuntimeStats is an autogenerated mock type for the RuntimeStats type
type MockRuntimeStats struct {
	mock.Mock
}

type MockRuntimeStats_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeStats) EXPECT() *MockRuntimeStats_Expecter {
	return &MockRuntimeStats_Expecter{mock: &_m.Mock}
}

// Stats provides a mock function with given fields: ctx, name
func (_m *MockRuntimeStats) Stats(ctx context.Context, name string) (runtime.Stats, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 runtime.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (runtime.Stats, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) runtime.Stats); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(runtime.Stats)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRuntimeStats_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockRuntimeStats_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRuntimeStats_Expecter) Stats(ctx interface{}, name interface{}) *MockRuntimeStats_Stats_Call {
	return &MockRuntimeStats_Stats_Call{Call: _e.mock.On("Stats", ctx, name)}
}

func (_c *MockRuntimeStats_Stats_Call) Run(run func(ctx context.Context, name string)) *MockRuntimeStats_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRuntimeStats_Stats_Call) Return(_a0 runtime.Stats, _a1 error) *MockRuntimeStats_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRuntimeStats_Stats_Call) RunAndReturn(run func(context.Context, string) (runtime.Stats, error)) *MockRuntimeStats_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuntimeStats creates a new instance of MockRuntimeStats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeStats(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeStats {
	mock := &MockRuntimeStats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
