// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	backup "github.com/AndrewOvvv/spawnling/internal/backup"
	mock "github.com/stretchr/testify/mock"
)

// MockArchiveStore is an autogenerated mock type for the ArchiveStore type
type MockArchiveStore struct {
	mock.Mock
}

type MockArchiveStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchiveStore) EXPECT() *MockArchiveStore_Expecter {
	return &MockArchiveStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: instanceName, worldPath
func (_m *MockArchiveStore) Create(instanceName string, worldPath string) (string, error) {
	ret := _m.Called(instanceName, worldPath)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(instanceName, worldPath)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(instanceName, worldPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(instanceName, worldPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchiveStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockArchiveStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - instanceName string
//   - worldPath string
func (_e *MockArchiveStore_Expecter) Create(instanceName interface{}, worldPath interface{}) *MockArchiveStore_Create_Call {
	return &MockArchiveStore_Create_Call{Call: _e.mock.On("Create", instanceName, worldPath)}
}

func (_c *MockArchiveStore_Create_Call) Run(run func(instanceName string, worldPath string)) *MockArchiveStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockArchiveStore_Create_Call) Return(archivePath string, err error) *MockArchiveStore_Create_Call {
	_c.Call.Return(archivePath, err)
	return _c
}

func (_c *MockArchiveStore_Create_Call) RunAndReturn(run func(string, string) (string, error)) *MockArchiveStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: instanceName
func (_m *MockArchiveStore) List(instanceName string) ([]backup.ArchiveMeta, error) {
	ret := _m.Called(instanceName)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []backup.ArchiveMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]backup.ArchiveMeta, error)); ok {
		return rf(instanceName)
	}
	if rf, ok := ret.Get(0).(func(string) []backup.ArchiveMeta); ok {
		r0 = rf(instanceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backup.ArchiveMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(instanceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchiveStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockArchiveStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - instanceName string
func (_e *MockArchiveStore_Expecter) List(instanceName interface{}) *MockArchiveStore_List_Call {
	return &MockArchiveStore_List_Call{Call: _e.mock.On("List", instanceName)}
}

func (_c *MockArchiveStore_List_Call) Run(run func(instanceName string)) *MockArchiveStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockArchiveStore_List_Call) Return(_a0 []backup.ArchiveMeta, _a1 error) *MockArchiveStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchiveStore_List_Call) RunAndReturn(run func(string) ([]backup.ArchiveMeta, error)) *MockArchiveStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function with given fields: instanceName, keepLast
func (_m *MockArchiveStore) Prune(instanceName string, keepLast int) error {
	ret := _m.Called(instanceName, keepLast)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(instanceName, keepLast)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchiveStore_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockArchiveStore_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - instanceName string
//   - keepLast int
func (_e *MockArchiveStore_Expecter) Prune(instanceName interface{}, keepLast interface{}) *MockArchiveStore_Prune_Call {
	return &MockArchiveStore_Prune_Call{Call: _e.mock.On("Prune", instanceName, keepLast)}
}

func (_c *MockArchiveStore_Prune_Call) Run(run func(instanceName string, keepLast int)) *MockArchiveStore_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockArchiveStore_Prune_Call) Return(_a0 error) *MockArchiveStore_Prune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchiveStore_Prune_Call) RunAndReturn(run func(string, int) error) *MockArchiveStore_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: archivePath, targetPath
func (_m *MockArchiveStore) Restore(archivePath string, targetPath string) error {
	ret := _m.Called(archivePath, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(archivePath, targetPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchiveStore_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockArchiveStore_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - archivePath string
//   - targetPath string
func (_e *MockArchiveStore_Expecter) Restore(archivePath interface{}, targetPath interface{}) *MockArchiveStore_Restore_Call {
	return &MockArchiveStore_Restore_Call{Call: _e.mock.On("Restore", archivePath, targetPath)}
}

func (_c *MockArchiveStore_Restore_Call) Run(run func(archivePath string, targetPath string)) *MockArchiveStore_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockArchiveStore_Restore_Call) Return(_a0 error) *MockArchiveStore_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchiveStore_Restore_Call) RunAndReturn(run func(string, string) error) *MockArchiveStore_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArchiveStore creates a new instance of MockArchiveStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchiveStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchiveStore {
	mock := &MockArchiveStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
