// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAgentRunner is an autogenerated mock type for the AgentRunner type
type MockAgentRunner struct {
	mock.Mock
}

type MockAgentRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRunner) EXPECT() *MockAgentRunner_Expecter {
	return &MockAgentRunner_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with given fields: instanceName
func (_m *MockAgentRunner) Address(instanceName string) (string, bool) {
	ret := _m.Called(instanceName)

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(instanceName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(instanceName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(instanceName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockAgentRunner_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockAgentRunner_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
//   - instanceName string
func (_e *MockAgentRunner_Expecter) Address(instanceName interface{}) *MockAgentRunner_Address_Call {
	return &MockAgentRunner_Address_Call{Call: _e.mock.On("Address", instanceName)}
}

func (_c *MockAgentRunner_Address_Call) Run(run func(instanceName string)) *MockAgentRunner_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAgentRunner_Address_Call) Return(_a0 string, _a1 bool) *MockAgentRunner_Address_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentRunner_Address_Call) RunAndReturn(run func(string) (string, bool)) *MockAgentRunner_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: instanceName, port
func (_m *MockAgentRunner) Start(instanceName string, port int) (string, error) {
	ret := _m.Called(instanceName, port)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return rf(instanceName, port)
	}
	if rf, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = rf(instanceName, port)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(instanceName, port)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAgentRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - instanceName string
//   - port int
func (_e *MockAgentRunner_Expecter) Start(instanceName interface{}, port interface{}) *MockAgentRunner_Start_Call {
	return &MockAgentRunner_Start_Call{Call: _e.mock.On("Start", instanceName, port)}
}

func (_c *MockAgentRunner_Start_Call) Run(run func(instanceName string, port int)) *MockAgentRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockAgentRunner_Start_Call) Return(address string, err error) *MockAgentRunner_Start_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *MockAgentRunner_Start_Call) RunAndReturn(run func(string, int) (string, error)) *MockAgentRunner_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: instanceName
func (_m *MockAgentRunner) Stop(instanceName string) error {
	ret := _m.Called(instanceName)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(instanceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockAgentRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - instanceName string
func (_e *MockAgentRunner_Expecter) Stop(instanceName interface{}) *MockAgentRunner_Stop_Call {
	return &MockAgentRunner_Stop_Call{Call: _e.mock.On("Stop", instanceName)}
}

func (_c *MockAgentRunner_Stop_Call) Run(run func(instanceName string)) *MockAgentRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAgentRunner_Stop_Call) Return(_a0 error) *MockAgentRunner_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentRunner_Stop_Call) RunAndReturn(run func(string) error) *MockAgentRunner_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentRunner creates a new instance of MockAgentRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRunner {
	mock := &MockAgentRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
