// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	process "github.com/AndrewOvvv/spawnling/internal/runtime/process"
	mock "github.com/stretchr/testify/mock"
)

// MockProcessSpawner is an autogenerated mock type for the ProcessSpawner type
type MockProcessSpawner struct {
	mock.Mock
}

type MockProcessSpawner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessSpawner) EXPECT() *MockProcessSpawner_Expecter {
	return &MockProcessSpawner_Expecter{mock: &_m.Mock}
}

// Spawn provides a mock function with given fields: javaPath, args, dir
func (_m *MockProcessSpawner) Spawn(javaPath string, args []string, dir string) (process.ProcessHandle, error) {
	ret := _m.Called(javaPath, args, dir)

	if len(ret) == 0 {
		panic("no return value specified for Spawn")
	}

	var r0 process.ProcessHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string, string) (process.ProcessHandle, error)); ok {
		return rf(javaPath, args, dir)
	}
	if rf, ok := ret.Get(0).(func(string, []string, string) process.ProcessHandle); ok {
		r0 = rf(javaPath, args, dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(process.ProcessHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string, string) error); ok {
		r1 = rf(javaPath, args, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProcessSpawner_Spawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spawn'
type MockProcessSpawner_Spawn_Call struct {
	*mock.Call
}

// Spawn is a helper method to define mock.On call
//   - javaPath string
//   - args []string
//   - dir string
func (_e *MockProcessSpawner_Expecter) Spawn(javaPath interface{}, args interface{}, dir interface{}) *MockProcessSpawner_Spawn_Call {
	return &MockProcessSpawner_Spawn_Call{Call: _e.mock.On("Spawn", javaPath, args, dir)}
}

func (_c *MockProcessSpawner_Spawn_Call) Run(run func(javaPath string, args []string, dir string)) *MockProcessSpawner_Spawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *MockProcessSpawner_Spawn_Call) Return(_a0 process.ProcessHandle, _a1 error) *MockProcessSpawner_Spawn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProcessSpawner_Spawn_Call) RunAndReturn(run func(string, []string, string) (process.ProcessHandle, error)) *MockProcessSpawner_Spawn_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessSpawner creates a new instance of MockProcessSpawner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessSpawner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessSpawner {
	mock := &MockProcessSpawner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
