// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockProcessHandle is an autogenerated mock type for the ProcessHandle type
type MockProcessHandle struct {
	mock.Mock
}

type MockProcessHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessHandle) EXPECT() *MockProcessHandle_Expecter {
	return &MockProcessHandle_Expecter{mock: &_m.Mock}
}

// Kill provides a mock function with no fields
func (_m *MockProcessHandle) Kill() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcessHandle_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockProcessHandle_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockProcessHandle_Expecter) Kill() *MockProcessHandle_Kill_Call {
	return &MockProcessHandle_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockProcessHandle_Kill_Call) Run(run func()) *MockProcessHandle_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessHandle_Kill_Call) Return(_a0 error) *MockProcessHandle_Kill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessHandle_Kill_Call) RunAndReturn(run func() error) *MockProcessHandle_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Pid provides a mock function with no fields
func (_m *MockProcessHandle) Pid() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pid")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockProcessHandle_Pid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pid'
type MockProcessHandle_Pid_Call struct {
	*mock.Call
}

// Pid is a helper method to define mock.On call
func (_e *MockProcessHandle_Expecter) Pid() *MockProcessHandle_Pid_Call {
	return &MockProcessHandle_Pid_Call{Call: _e.mock.On("Pid")}
}

func (_c *MockProcessHandle_Pid_Call) Run(run func()) *MockProcessHandle_Pid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessHandle_Pid_Call) Return(_a0 int) *MockProcessHandle_Pid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessHandle_Pid_Call) RunAndReturn(run func() int) *MockProcessHandle_Pid_Call {
	_c.Call.Return(run)
	return _c
}

// Stdin provides a mock function with no fields
func (_m *MockProcessHandle) Stdin() io.WriteCloser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdin")
	}

	var r0 io.WriteCloser
	if rf, ok := ret.Get(0).(func() io.WriteCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	return r0
}

// MockProcessHandle_Stdin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdin'
type MockProcessHandle_Stdin_Call struct {
	*mock.Call
}

// Stdin is a helper method to define mock.On call
func (_e *MockProcessHandle_Expecter) Stdin() *MockProcessHandle_Stdin_Call {
	return &MockProcessHandle_Stdin_Call{Call: _e.mock.On("Stdin")}
}

func (_c *MockProcessHandle_Stdin_Call) Run(run func()) *MockProcessHandle_Stdin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessHandle_Stdin_Call) Return(_a0 io.WriteCloser) *MockProcessHandle_Stdin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessHandle_Stdin_Call) RunAndReturn(run func() io.WriteCloser) *MockProcessHandle_Stdin_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function with no fields
func (_m *MockProcessHandle) Stdout() io.ReadCloser {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	return r0
}

// MockProcessHandle_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type MockProcessHandle_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *MockProcessHandle_Expecter) Stdout() *MockProcessHandle_Stdout_Call {
	return &MockProcessHandle_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *MockProcessHandle_Stdout_Call) Run(run func()) *MockProcessHandle_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessHandle_Stdout_Call) Return(_a0 io.ReadCloser) *MockProcessHandle_Stdout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessHandle_Stdout_Call) RunAndReturn(run func() io.ReadCloser) *MockProcessHandle_Stdout_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with no fields
func (_m *MockProcessHandle) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProcessHandle_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockProcessHandle_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockProcessHandle_Expecter) Wait() *MockProcessHandle_Wait_Call {
	return &MockProcessHandle_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockProcessHandle_Wait_Call) Run(run func()) *MockProcessHandle_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessHandle_Wait_Call) Return(_a0 error) *MockProcessHandle_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessHandle_Wait_Call) RunAndReturn(run func() error) *MockProcessHandle_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessHandle creates a new instance of MockProcessHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessHandle {
	mock := &MockProcessHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
