// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	process "github.com/AndrewOvvv/spawnling/internal/runtime/process"
	mock "github.com/stretchr/testify/mock"
)

// MockLogStreamFactory is an autogenerated mock type for the LogStreamFactory type
type MockLogStreamFactory struct {
	mock.Mock
}

type MockLogStreamFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogStreamFactory) EXPECT() *MockLogStreamFactory_Expecter {
	return &MockLogStreamFactory_Expecter{mock: &_m.Mock}
}

// NewLogStream provides a mock function with no fields
func (_m *MockLogStreamFactory) NewLogStream() process.LogStream {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewLogStream")
	}

	var r0 process.LogStream
	if rf, ok := ret.Get(0).(func() process.LogStream); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(process.LogStream)
		}
	}

	return r0
}

// MockLogStreamFactory_NewLogStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewLogStream'
type MockLogStreamFactory_NewLogStream_Call struct {
	*mock.Call
}

// NewLogStream is a helper method to define mock.On call
func (_e *MockLogStreamFactory_Expecter) NewLogStream() *MockLogStreamFactory_NewLogStream_Call {
	return &MockLogStreamFactory_NewLogStream_Call{Call: _e.mock.On("NewLogStream")}
}

func (_c *MockLogStreamFactory_NewLogStream_Call) Run(run func()) *MockLogStreamFactory_NewLogStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogStreamFactory_NewLogStream_Call) Return(_a0 process.LogStream) *MockLogStreamFactory_NewLogStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogStreamFactory_NewLogStream_Call) RunAndReturn(run func() process.LogStream) *MockLogStreamFactory_NewLogStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogStreamFactory creates a new instance of MockLogStreamFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogStreamFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogStreamFactory {
	mock := &MockLogStreamFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
