// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockLogStream is an autogenerated mock type for the LogStream type
type MockLogStream struct {
	mock.Mock
}

type MockLogStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogStream) EXPECT() *MockLogStream_Expecter {
	return &MockLogStream_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockLogStream) Close() {
	_m.Called()
}

// MockLogStream_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLogStream_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLogStream_Expecter) Close() *MockLogStream_Close_Call {
	return &MockLogStream_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLogStream_Close_Call) Run(run func()) *MockLogStream_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogStream_Close_Call) Return() *MockLogStream_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogStream_Close_Call) RunAndReturn(run func()) *MockLogStream_Close_Call {
	_c.Run(run)
	return _c
}

// Reader provides a mock function with given fields: ctx
func (_m *MockLogStream) Reader(ctx context.Context) io.ReadCloser {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context) io.ReadCloser); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	return r0
}

// MockLogStream_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type MockLogStream_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLogStream_Expecter) Reader(ctx interface{}) *MockLogStream_Reader_Call {
	return &MockLogStream_Reader_Call{Call: _e.mock.On("Reader", ctx)}
}

func (_c *MockLogStream_Reader_Call) Run(run func(ctx context.Context)) *MockLogStream_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLogStream_Reader_Call) Return(_a0 io.ReadCloser) *MockLogStream_Reader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogStream_Reader_Call) RunAndReturn(run func(context.Context) io.ReadCloser) *MockLogStream_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLine provides a mock function with given fields: line
func (_m *MockLogStream) WriteLine(line string) {
	_m.Called(line)
}

// MockLogStream_WriteLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLine'
type MockLogStream_WriteLine_Call struct {
	*mock.Call
}

// WriteLine is a helper method to define mock.On call
//   - line string
func (_e *MockLogStream_Expecter) WriteLine(line interface{}) *MockLogStream_WriteLine_Call {
	return &MockLogStream_WriteLine_Call{Call: _e.mock.On("WriteLine", line)}
}

func (_c *MockLogStream_WriteLine_Call) Run(run func(line string)) *MockLogStream_WriteLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLogStream_WriteLine_Call) Return() *MockLogStream_WriteLine_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogStream_WriteLine_Call) RunAndReturn(run func(string)) *MockLogStream_WriteLine_Call {
	_c.Run(run)
	return _c
}

// NewMockLogStream creates a new instance of MockLogStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogStream {
	mock := &MockLogStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
