// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: path
func (_m *MockFileSystem) Exists(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFileSystem_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) Exists(path interface{}) *MockFileSystem_Exists_Call {
	return &MockFileSystem_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *MockFileSystem_Exists_Call) Run(run func(path string)) *MockFileSystem_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Exists_Call) Return(_a0 bool, _a1 error) *MockFileSystem_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Exists_Call) RunAndReturn(run func(string) (bool, error)) *MockFileSystem_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: path, perm
func (_m *MockFileSystem) MkdirAll(path string, perm fs.FileMode) error {
	ret := _m.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(path, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFileSystem_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileSystem_MkdirAll_Call {
	return &MockFileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileSystem_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileMode))
	})
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) Return(_a0 error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) RunAndReturn(run func(string, fs.FileMode) error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: path
func (_m *MockFileSystem) ReadFile(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) ReadFile(path interface{}) *MockFileSystem_ReadFile_Call {
	return &MockFileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockFileSystem_ReadFile_Call) Run(run func(path string)) *MockFileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *MockFileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: path
func (_m *MockFileSystem) RemoveAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockFileSystem_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileSystem_Expecter) RemoveAll(path interface{}) *MockFileSystem_RemoveAll_Call {
	return &MockFileSystem_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockFileSystem_RemoveAll_Call) Run(run func(path string)) *MockFileSystem_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_RemoveAll_Call) Return(_a0 error) *MockFileSystem_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_RemoveAll_Call) RunAndReturn(run func(string) error) *MockFileSystem_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: path, data, perm
func (_m *MockFileSystem) WriteFile(path string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileSystem_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm fs.FileMode
func (_e *MockFileSystem_Expecter) WriteFile(path interface{}, data interface{}, perm interface{}) *MockFileSystem_WriteFile_Call {
	return &MockFileSystem_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data, perm)}
}

func (_c *MockFileSystem_WriteFile_Call) Run(run func(path string, data []byte, perm fs.FileMode)) *MockFileSystem_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) Return(_a0 error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_WriteFile_Call) RunAndReturn(run func(string, []byte, fs.FileMode) error) *MockFileSystem_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
