// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockProcStats is an autogenerated mock type for the ProcStats type
type MockProcStats struct {
	mock.Mock
}

type MockProcStats_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcStats) EXPECT() *MockProcStats_Expecter {
	return &MockProcStats_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: pid
func (_m *MockProcStats) Read(pid int) (float64, int, error) {
	ret := _m.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (float64, int, error)); ok {
		return rf(pid)
	}
	if rf, ok := ret.Get(0).(func(int) float64); ok {
		r0 = rf(pid)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(int) int); ok {
		r1 = rf(pid)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(pid)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProcStats_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockProcStats_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - pid int
func (_e *MockProcStats_Expecter) Read(pid interface{}) *MockProcStats_Read_Call {
	return &MockProcStats_Read_Call{Call: _e.mock.On("Read", pid)}
}

func (_c *MockProcStats_Read_Call) Run(run func(pid int)) *MockProcStats_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockProcStats_Read_Call) Return(cpuPct float64, memMB int, err error) *MockProcStats_Read_Call {
	_c.Call.Return(cpuPct, memMB, err)
	return _c
}

func (_c *MockProcStats_Read_Call) RunAndReturn(run func(int) (float64, int, error)) *MockProcStats_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcStats creates a new instance of MockProcStats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcStats(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcStats {
	mock := &MockProcStats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
