// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/AndrewOvvv/spawnling/internal/runtime"
)

// MockJARProvider is an autogenerated mock type for the JARProvider type
type MockJARProvider struct {
	mock.Mock
}

type MockJARProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJARProvider) EXPECT() *MockJARProvider_Expecter {
	return &MockJARProvider_Expecter{mock: &_m.Mock}
}

// Ensure provides a mock function with given fields: ctx, spec, destPath
func (_m *MockJARProvider) Ensure(ctx context.Context, spec runtime.InstanceSpec, destPath string) error {
	ret := _m.Called(ctx, spec, destPath)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, runtime.InstanceSpec, string) error); ok {
		r0 = rf(ctx, spec, destPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJARProvider_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockJARProvider_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - spec runtime.InstanceSpec
//   - destPath string
func (_e *MockJARProvider_Expecter) Ensure(ctx interface{}, spec interface{}, destPath interface{}) *MockJARProvider_Ensure_Call {
	return &MockJARProvider_Ensure_Call{Call: _e.mock.On("Ensure", ctx, spec, destPath)}
}

func (_c *MockJARProvider_Ensure_Call) Run(run func(ctx context.Context, spec runtime.InstanceSpec, destPath string)) *MockJARProvider_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(runtime.InstanceSpec), args[2].(string))
	})
	return _c
}

func (_c *MockJARProvider_Ensure_Call) Return(_a0 error) *MockJARProvider_Ensure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJARProvider_Ensure_Call) RunAndReturn(run func(context.Context, runtime.InstanceSpec, string) error) *MockJARProvider_Ensure_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJARProvider creates a new instance of MockJARProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJARProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJARProvider {
	mock := &MockJARProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
