// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	runtime "github.com/AndrewOvvv/spawnling/internal/runtime"
)

// MockRuntimeBackend is an autogenerated mock type for the RuntimeBackend type
type MockRuntimeBackend struct {
	mock.Mock
}

type MockRuntimeBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntimeBackend) EXPECT() *MockRuntimeBackend_Expecter {
	return &MockRuntimeBackend_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, spec
func (_m *MockRuntimeBackend) Create(ctx context.Context, spec runtime.InstanceSpec) error {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, runtime.InstanceSpec) error); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRuntimeBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRuntimeBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec runtime.InstanceSpec
func (_e *MockRuntimeBackend_Expecter) Create(ctx interface{}, spec interface{}) *MockRuntimeBackend_Create_Call {
	return &MockRuntimeBackend_Create_Call{Call: _e.mock.On("Create", ctx, spec)}
}

func (_c *MockRuntimeBackend_Create_Call) Run(run func(ctx context.Context, spec runtime.InstanceSpec)) *MockRuntimeBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(runtime.InstanceSpec))
	})
	return _c
}

func (_c *MockRuntimeBackend_Create_Call) Return(_a0 error) *MockRuntimeBackend_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuntimeBackend_Create_Call) RunAndReturn(run func(context.Context, runtime.InstanceSpec) error) *MockRuntimeBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name
func (_m *MockRuntimeBackend) Delete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRuntimeBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRuntimeBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRuntimeBackend_Expecter) Delete(ctx interface{}, name interface{}) *MockRuntimeBackend_Delete_Call {
	return &MockRuntimeBackend_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockRuntimeBackend_Delete_Call) Run(run func(ctx context.Context, name string)) *MockRuntimeBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRuntimeBackend_Delete_Call) Return(_a0 error) *MockRuntimeBackend_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuntimeBackend_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRuntimeBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuntimeBackend creates a new instance of MockRuntimeBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntimeBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntimeBackend {
	mock := &MockRuntimeBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
