// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	instance "github.com/AndrewOvvv/spawnling/internal/instance"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigStore is an autogenerated mock type for the ConfigStore type
type MockConfigStore struct {
	mock.Mock
}

type MockConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigStore) EXPECT() *MockConfigStore_Expecter {
	return &MockConfigStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: name
func (_m *MockConfigStore) Delete(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConfigStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - name string
func (_e *MockConfigStore_Expecter) Delete(name interface{}) *MockConfigStore_Delete_Call {
	return &MockConfigStore_Delete_Call{Call: _e.mock.On("Delete", name)}
}

func (_c *MockConfigStore_Delete_Call) Run(run func(name string)) *MockConfigStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigStore_Delete_Call) Return(_a0 error) *MockConfigStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigStore_Delete_Call) RunAndReturn(run func(string) error) *MockConfigStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with no fields
func (_m *MockConfigStore) List() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockConfigStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockConfigStore_Expecter) List() *MockConfigStore_List_Call {
	return &MockConfigStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockConfigStore_List_Call) Run(run func()) *MockConfigStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigStore_List_Call) Return(_a0 []string, _a1 error) *MockConfigStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigStore_List_Call) RunAndReturn(run func() ([]string, error)) *MockConfigStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: name
func (_m *MockConfigStore) Load(name string) (*instance.Config, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *instance.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*instance.Config, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *instance.Config); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*instance.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - name string
func (_e *MockConfigStore_Expecter) Load(name interface{}) *MockConfigStore_Load_Call {
	return &MockConfigStore_Load_Call{Call: _e.mock.On("Load", name)}
}

func (_c *MockConfigStore_Load_Call) Run(run func(name string)) *MockConfigStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigStore_Load_Call) Return(_a0 *instance.Config, _a1 error) *MockConfigStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigStore_Load_Call) RunAndReturn(run func(string) (*instance.Config, error)) *MockConfigStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: name, cfg
func (_m *MockConfigStore) Save(name string, cfg *instance.Config) error {
	ret := _m.Called(name, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *instance.Config) error); ok {
		r0 = rf(name, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConfigStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - name string
//   - cfg *instance.Config
func (_e *MockConfigStore_Expecter) Save(name interface{}, cfg interface{}) *MockConfigStore_Save_Call {
	return &MockConfigStore_Save_Call{Call: _e.mock.On("Save", name, cfg)}
}

func (_c *MockConfigStore_Save_Call) Run(run func(name string, cfg *instance.Config)) *MockConfigStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*instance.Config))
	})
	return _c
}

func (_c *MockConfigStore_Save_Call) Return(_a0 error) *MockConfigStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigStore_Save_Call) RunAndReturn(run func(string, *instance.Config) error) *MockConfigStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigStore creates a new instance of MockConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigStore {
	mock := &MockConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
